/** @type {import('tailwindcss').Config} */
// Design tokens transcribed 1:1 from DESIGN.md (Coursewright / Stitch export).
// Color keys are kept flat + kebab-case to match DESIGN.md exactly, so class
// names copied straight out of the reference screens (e.g. `bg-surface-card`,
// `text-on-primary-container`) resolve correctly without translation.
export default {
    content: ['./index.html', './src/**/*.{js,jsx}'],
    theme: {
      extend: {
        colors: {
          primary: '#e60023',
          'on-primary': '#ffffff',
          'primary-pressed': '#cc001f',
          ink: '#000000',
          'ink-soft': '#211922',
          body: '#33332e',
          charcoal: '#262622',
          mute: '#62625b',
          ash: '#91918c',
          stone: '#c8c8c1',
          hairline: '#dadad3',
          'hairline-soft': '#e5e5e0',
          'on-secondary': '#000000',
          'secondary-bg': '#e5e5e0',
          'secondary-pressed': '#c8c8c1',
          canvas: '#ffffff',
          'surface-soft': '#fbfbf9',
          'surface-card': '#f6f6f3',
          'surface-elevated': '#ffffff',
          'on-dark': '#ffffff',
          'on-dark-mute': 'rgba(255,255,255,0.7)',
          'surface-dark': '#262622',
          'focus-outer': '#435ee5',
          'focus-inner': '#ffffff',
          surface: '#fff8f7',
          'surface-dim': '#f5d2cf',
          'surface-bright': '#fff8f7',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#fff0ef',
          'surface-container': '#ffe9e7',
          'surface-container-high': '#ffe2df',
          'surface-container-highest': '#fedad7',
          'on-surface': '#2a1615',
          'on-surface-variant': '#5e3f3c',
          'inverse-surface': '#412b29',
          'inverse-on-surface': '#ffedeb',
          outline: '#936e6b',
          'outline-variant': '#e8bcb8',
          'surface-tint': '#c0001b',
          'primary-container': '#e60023',
          'on-primary-container': '#fff7f6',
          'inverse-primary': '#ffb3ad',
          secondary: '#5d5f5b',
          'secondary-container': '#e0e0db',
          'on-secondary-container': '#62635f',
          tertiary: '#005f90',
          'on-tertiary': '#ffffff',
          'tertiary-container': '#0079b6',
          'on-tertiary-container': '#f7f9ff',
          error: '#ba1a1a',
          'on-error': '#ffffff',
          'error-container': '#ffdad6',
          'on-error-container': '#93000a',
          'primary-fixed': '#ffdad7',
          'primary-fixed-dim': '#ffb3ad',
          'on-primary-fixed': '#410004',
          'on-primary-fixed-variant': '#930012',
          'secondary-fixed': '#e3e3de',
          'secondary-fixed-dim': '#c6c7c2',
          'on-secondary-fixed': '#1a1c19',
          'on-secondary-fixed-variant': '#464744',
          'tertiary-fixed': '#cce5ff',
          'tertiary-fixed-dim': '#92ccff',
          'on-tertiary-fixed': '#001e31',
          'on-tertiary-fixed-variant': '#004b73',
          background: '#fff8f7',
          'on-background': '#2a1615',
          'surface-variant': '#fedad7',
          'body-text': '#33332e',
        },
        fontFamily: {
          'display-xl': ['Inter', 'sans-serif'],
          'display-lg': ['Inter', 'sans-serif'],
          'display-lg-mobile': ['Inter', 'sans-serif'],
          'heading-xl': ['Inter', 'sans-serif'],
          'heading-lg': ['Inter', 'sans-serif'],
          'heading-md': ['Inter', 'sans-serif'],
          'body-md': ['Inter', 'sans-serif'],
          'body-strong': ['Inter', 'sans-serif'],
          'body-sm': ['Inter', 'sans-serif'],
          'body-sm-strong': ['Inter', 'sans-serif'],
          'button-md': ['Inter', 'sans-serif'],
        },
        fontSize: {
          'display-xl': ['70px', { lineHeight: '1.1', letterSpacing: '-1.2px', fontWeight: '600' }],
          'display-lg': ['44px', { lineHeight: '1.15', letterSpacing: '-0.8px', fontWeight: '700' }],
          'display-lg-mobile': ['32px', { lineHeight: '1.2', letterSpacing: '-0.5px', fontWeight: '700' }],
          'heading-xl': ['28px', { lineHeight: '1.2', letterSpacing: '-1.2px', fontWeight: '700' }],
          'heading-lg': ['22px', { lineHeight: '1.25', letterSpacing: '0px', fontWeight: '600' }],
          'heading-md': ['18px', { lineHeight: '1.3', letterSpacing: '0px', fontWeight: '600' }],
          'body-md': ['16px', { lineHeight: '1.4', letterSpacing: '0px', fontWeight: '400' }],
          'body-strong': ['16px', { lineHeight: '1.4', letterSpacing: '0px', fontWeight: '600' }],
          'body-sm': ['14px', { lineHeight: '1.4', letterSpacing: '0px', fontWeight: '400' }],
          'body-sm-strong': ['14px', { lineHeight: '1.4', letterSpacing: '0px', fontWeight: '700' }],
          'button-md': ['14px', { lineHeight: '1', letterSpacing: '0px', fontWeight: '700' }],
        },
        spacing: {
          xxs: '4px',
          xs: '6px',
          sm: '8px',
          md: '12px',
          lg: '16px',
          xl: '24px',
          xxl: '32px',
          section: '64px',
          gutter: '16px',
          margin: '24px',
        },
        borderRadius: {
          none: '0px',
          sm: '8px',
          DEFAULT: '0.5rem',
          md: '16px',
          lg: '32px',
          xl: '1.5rem',
          full: '9999px',
        },
      },
    },
    plugins: [],
  }